### ISSUE TITLE
BUG | SOme fucntion should not return an empty array

### ISSUE THREAD

**Issue by kingabzpro** [v1a0/sqllex#25]
## ✅ DESCRIBE THE BUG 
The code about inserts or any other function except select should not return anything not even empty array 

## ✅ CODE
The code about inserts or any other function except select should not return anything not even empty array 

For example:
```python
vaccine_db.insertmany('Total',data.drop(columns= "Date_Time",axis =1).values)
```

## SCREENSHOTS
![image](https://user-images.githubusercontent.com/36753484/121803333-7828e100-cc5a-11eb-99c4-76d763ec8072.png)

## ⚠️ CONFIGURATIONS
 - OS: Linux
 - Python version: 3.8
 - Sqllex version: v0.1.9.4

**Comment by v1a0** [comment]
Hey @kingabzpro, thanks for opening new issue. 

I agree that some methods don't have to return nothing but now it's happens and that why:

Many SQLite3x's methods have argument `execute`, if it's **True** method will execute generated SQL-script and return `[ ]` like NOTHING, if it's **False** it will return SQLStatement object, it contains generated script and values.

```python
stmt = table.select(
    WHERE={'group_id': 4},
    execute=False
)
script = stmt.request.script 
values = stmt.request.values 

print(script)
# "SELECT * FROM users WHERE (group_id=?)"

print(values)
# (4, )
```

I'm not really sure is in necessary to leave this argument or just remove it, because by now it looks useless...
What do you thinks, should we remove this feature or not? 

Because it'll be reasonable remove this feature and fix this issue at the same update.

**Comment by kingabzpro** [comment]
I think for select a related function requires it but modification and other methods should avoid it. You can remove the function but it will affect the elect notion too. So I think we should come up with a dynamic solution that will not affect any select related functions.

**Comment by v1a0** [comment]
I had some troubles with publishing release v0.1.9.5, so please update up to v0.1.9.6 and let me know is this issue fixed.

**Comment by v1a0** [comment]
So I just removed `execute` argument for all public methods, don't think it's useful feature.

**Comment by kingabzpro** [comment]
Yes, its removed now. Thank you
